config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root 'fourteeners#index'
	devise_for :users
	resources :fourteeners
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fourteener.rb
class Fourteener < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/fourteeners_controller.rb
class FourteenersController < ApplicationController
  before_action :set_fourteener, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin, only: [:new, :create, :edit, :update, :destroy]

  def authenticate_admin
    unless current_user.present? and current_user.admin?
      redirect_to new_user_session_url, notice: "You must be an administrator to access this page."
    end
  end

  # GET /fourteeners
  # GET /fourteeners.json
  def index
    # @fourteeners = Fourteener.all
    gon.fourteeners = Fourteener.all
  end

  # GET /fourteeners/1
  # GET /fourteeners/1.json
  def show
    gon.fourteener = Fourteener.find(params[:id])
  end

  # GET /fourteeners/new
  def new
    @fourteener = Fourteener.new
  end

  # GET /fourteeners/1/edit
  def edit
  end

  # POST /fourteeners
  # POST /fourteeners.json
  def create
    @fourteener = Fourteener.new(fourteener_params)

    respond_to do |format|
      if @fourteener.save
        format.html { redirect_to @fourteener, notice: 'Fourteener was successfully created.' }
        format.json { render :show, status: :created, location: @fourteener }
      else
        format.html { render :new }
        format.json { render json: @fourteener.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fourteeners/1
  # PATCH/PUT /fourteeners/1.json
  def update
    respond_to do |format|
      if @fourteener.update(fourteener_params)
        format.html { redirect_to @fourteener, notice: 'Fourteener was successfully updated.' }
        format.json { render :show, status: :ok, location: @fourteener }
      else
        format.html { render :edit }
        format.json { render json: @fourteener.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fourteeners/1
  # DELETE /fourteeners/1.json
  def destroy
    @fourteener.destroy
    respond_to do |format|
      format.html { redirect_to fourteeners_url, notice: 'Fourteener was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fourteener
      @fourteener = Fourteener.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fourteener_params
      params.require(:fourteener).permit(:name, :surname, :elevation_in_feet, :rank, :location_lat, :location_long, :forest, :range, :classification, :exposure, :elevation_gain_in_feet, :round_trip_distance_in_miles, :no_4wd_additional_elevation_in_feet, :no_4wd_additional_distance_in_miles, :route_name, :trailhead_name, :trailhead_lat, :trailhead_long, :four_x_four_required, :additional_info_url, :description, :kml)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fourteeners_helper.rb
module FourteenersHelper
end

app/views/fourteeners/_form.html.erb
<%= form_for(fourteener) do |f| %>
  <% if fourteener.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fourteener.errors.count, "error") %> prohibited this fourteener from being saved:</h2>

      <ul>
      <% fourteener.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :surname %>
    <%= f.text_field :surname %>
  </div>

  <div class="field">
    <%= f.label :elevation_in_feet %>
    <%= f.number_field :elevation_in_feet %>
  </div>

  <div class="field">
    <%= f.label :rank %>
    <%= f.number_field :rank %>
  </div>

  <div class="field">
    <%= f.label :location_lat %>
    <%= f.text_field :location_lat %>
  </div>

  <div class="field">
    <%= f.label :location_long %>
    <%= f.text_field :location_long %>
  </div>

  <div class="field">
    <%= f.label :forest %>
    <%= f.text_field :forest %>
  </div>

  <div class="field">
    <%= f.label :range %>
    <%= f.text_field :range %>
  </div>

  <div class="field">
    <%= f.label :classification %>
    <%= f.text_field :classification %>
  </div>

  <div class="field">
    <%= f.label :exposure %>
    <%= f.number_field :exposure %>
  </div>

  <div class="field">
    <%= f.label :elevation_gain_in_feet %>
    <%= f.number_field :elevation_gain_in_feet %>
  </div>

  <div class="field">
    <%= f.label :round_trip_distance_in_miles %>
    <%= f.text_field :round_trip_distance_in_miles %>
  </div>

  <div class="field">
    <%= f.label :no_4wd_additional_elevation_in_feet %>
    <%= f.number_field :no_4wd_additional_elevation_in_feet %>
  </div>

  <div class="field">
    <%= f.label :no_4wd_additional_distance_in_miles %>
    <%= f.text_field :no_4wd_additional_distance_in_miles %>
  </div>

  <div class="field">
    <%= f.label :route_name %>
    <%= f.text_field :route_name %>
  </div>

  <div class="field">
    <%= f.label :trailhead_name %>
    <%= f.text_field :trailhead_name %>
  </div>

  <div class="field">
    <%= f.label :trailhead_lat %>
    <%= f.text_field :trailhead_lat %>
  </div>

  <div class="field">
    <%= f.label :trailhead_long %>
    <%= f.text_field :trailhead_long %>
  </div>

  <div class="field">
    <%= f.label :four_x_four_required %>
    <%= f.text_field :four_x_four_required %>
  </div>

  <div class="field">
    <%= f.label :additional_info_url %>
    <%= f.text_field :additional_info_url %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :kml %>
    <%= f.text_field :kml %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fourteeners/edit.html.erb
<h1>Editing Fourteener</h1>

<%= render 'form', fourteener: @fourteener %>

<%= link_to 'Show', @fourteener %> |
<%= link_to 'Back', fourteeners_path %>

app/views/fourteeners/index.html.erb
<%= include_gon(:init => true) %>

<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

		<div id="map"></div>
		<div id="sidebar">
			<h6 style="padding-left: 10px; text-align: center; color: white;"><i> Use sliders and check boxes to find the right peak for you.</i></h6>
			<fieldset>
				<legend>Difficulty: </legend>

				<input type="checkbox" class="filled-in" id="class1" checked/>
				<label for="class1">Class 1 &nbsp </label>

				<input type="checkbox" class="filled-in" id="class2" checked/>
				<label for="class2">Class 2 &nbsp </label>

				<input type="checkbox" class="filled-in" id="class3" checked/>
				<label for="class3">Class 3 &nbsp </label>

				<input type="checkbox" class="filled-in" id="class4" checked/>
				<label for="class4">Class 4 &nbsp </label>

			</fieldset>

			<!-- <fieldset>
				<legend>Four-Wheel Clearance: </legend>

				<input type="checkbox" class="filled-in" id="2wd" checked/>
				<label for="2wd">2WD &nbsp </label>

				<input type="checkbox" class="filled-in" id="2hc"/>
				<label for="2hc">High-Clearance 2WD &nbsp </label>

				<input type="checkbox" class="filled-in" id="awd"/>
				<label for="awd">AWD &nbsp </label>

				<input type="checkbox" class="filled-in" id="4x4"/>
				<label for="4x4">4x4 &nbsp </label>
			</fieldset> -->

			<div style="max-width: 300px; padding-left:15px;">
				<p><label for="vehicle">Trailhead Accessibility</label><input type="text" id="vehicle" readonly style="border:0; color:#f6931f; font-weight:bold;"></p>
				<div id="slider-vehicle"></div>

				<p><label for="elevation">Elevation Gain:</label><input type="text" id="elevation" readonly style="border:0; color:#f6931f; font-weight:bold;"></p>
				<div id="slider-elevation"></div>

				<p><label for="distance">Round Trip Distance:</label><input type="text" id="distance" readonly style="border:0; color:#f6931f; font-weight:bold;"></p>
				<div id="slider-distance"></div>
			</div>
		</div>

<script async src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBBYkGDkbDQBSWK4WoQM-r8tA5WXkqu_Rw&callback=initMap"></script>
<script type="text/javascript">
	var markers = []; //array of markers
	function initMap() {
		var castle = {lat: 39.180945, lng:-107.2416232};
		var map = new google.maps.Map(document.getElementById('map'), {
			zoom: 7,
			center: castle,
			mapTypeId: 'hybrid'
		});
		var infowindow = new google.maps.InfoWindow();
		gon.fourteeners.forEach(function(fourteener){
			if (fourteener.surname == "Mount") {
				var full_name = fourteener.surname + " " +fourteener.name;
			} else if (fourteener.surname == "Peak"){
				var full_name = fourteener.name + " " + fourteener.surname;
			} else if (fourteener.surname == "Mount of the "){
				var full_name = fourteener.surname + " " + fourteener.name;
			} else if (fourteener.surname == "Mountain"){
				var full_name = fourteener.name + " " + fourteener.surname;
			} else if (fourteener.surname == "Needle"){
				var full_name = fourteener.name + " " + fourteener.surname;
			} else if (fourteener.surname == "Point"){
				var full_name = fourteener.name + " " + fourteener.surname;
			} else {
				var full_name = fourteener.name;
			}
			var marker = new google.maps.Marker({
				position: {lat: fourteener.location_lat, lng: fourteener.location_long},
				map: map,
				title: full_name,
				surname: fourteener.surname,
				elevation_in_feet: fourteener.elevation_in_feet,
				rank: fourteener.rank,
				location_lat: fourteener.location_lat,
				location_long: fourteener.location_long,
				forest: fourteener.forest,
				range: fourteener.range,
				classification: fourteener.classification,
				exposure: fourteener.exposure,
				elevation_gain_in_feet: fourteener.elevation_gain_in_feet,
				round_trip_distance_in_miles: fourteener.round_trip_distance_in_miles,
				no_4wd_additional_elevation_in_feet: fourteener.no_4wd_additional_elevation_in_feet,
				no_4wd_additional_distance_in_miles: fourteener.no_4wd_additional_distance_in_miles,
				route_name: fourteener.route_name,
				trailhead_name: fourteener.trailhead_name,
				trailhead_lat: fourteener.trailhead_lat,
				trailhead_long: fourteener.trailhead_long,
				four_x_four_required: fourteener.four_x_four_required,
				additional_info_url: fourteener.additional_info_url,
				kml: fourteener.kml
			});
			if (marker.classification < 2) {
				marker.setIcon('http://maps.google.com/mapfiles/ms/icons/green-dot.png');
			} else if (marker.classification < 3) {
				marker.setIcon('http://maps.google.com/mapfiles/ms/icons/blue-dot.png');
			} else if (marker.classification < 4) {
				marker.setIcon('http://maps.google.com/mapfiles/ms/icons/yellow-dot.png');
			} else  {
				marker.setIcon('http://maps.google.com/mapfiles/ms/icons/red-dot.png');
			}
			markers.push(marker); //add marker to array of markers
			var contentString = '<div id="content">'+
			  '<div id="siteNotice">'+
			  '</div>'+
			  '<h1 id="firstHeading" class="firstHeading">'+full_name+'</h1>'+
			  '<div id="bodyContent">'+
			  '<p>Elevation: '+marker.elevation_in_feet+' feet</br>'+
			  'Class: '+marker.classification+'</br>'+
			  'Range: '+marker.range+'</br>'+
			  'Forest: '+marker.forest+'</br>'+
			  'Route name: '+marker.route_name+'</br>'+
			  'Trailhead name: '+marker.trailhead_name+'</br>'+
			  'Round trip distance: '+marker.round_trip_distance_in_miles+' miles</br>'+
			  'Elevation gain: '+marker.elevation_gain_in_feet+' feet</br></p>'+
			  '<p><a style="color:black !important;" href=\"fourteeners/' + marker.rank + '\">More Info</a></p>'+
			  '</div>'+
			  '</div>';
			marker.addListener('click', function() {
				map.setZoom(11);
				map.setCenter(marker.getPosition());
				infowindow.setContent(contentString);
				infowindow.setPosition(marker.getPosition());
				infowindow.open(marker.get('map'), marker);
			});
		});
	}
	

	function visible(marker){
		return marker.visible
	}

	function classOnes(marker){
		return marker.classification < 2;
	}

	function classTwos(marker){
		return marker.classification < 3 && marker.classification >= 2;
	}

	function classThrees(marker){
		return marker.classification < 4 && marker.classification >= 3;
	}

	function classFours(marker){
		return marker.classification < 5 && marker.classification >= 4;
	}

	function twoWheelDrive(marker){
		return marker.four_x_four_required == 0;
	}

	function twoHighClearance(marker){
		return marker.four_x_four_required < 1;
	}

	function allWheelDrive(marker){
		return marker.four_x_four_required > 1;
	}

	function fourByFour(marker){
		return marker.four_x_four_required = 2 ;
	}

	$('#class1').change(function(){
		if( !$(this)[0].checked ){
			var ones = markers.filter(classOnes);
			$.each(ones, function(i, marker){
				marker.setVisible(false);
			});
		}
		else{
			var ones = markers.filter(classOnes);
			$.each(ones, function(i, marker){
				marker.setVisible(true);
			});
		}
	});

	$('#class2').change(function(){
		if( !$(this)[0].checked ){
			var ones = markers.filter(classTwos);
			$.each(ones, function(i, marker){
				marker.setVisible(false);
			});
		}
		else{
			var ones = markers.filter(classTwos);
			$.each(ones, function(i, marker){
				marker.setVisible(true);
			});
		}
	});

	$('#class3').change(function(){
		if( !$(this)[0].checked ){
			var ones = markers.filter(classThrees);
			$.each(ones, function(i, marker){
				marker.setVisible(false);
			});
		}
		else{
			var ones = markers.filter(classThrees);
			$.each(ones, function(i, marker){
				marker.setVisible(true);
			});
		}
	});

	$('#class4').change(function(){
		if( !$(this)[0].checked ){
			var ones = markers.filter(classFours);
			$.each(ones, function(i, marker){
				marker.setVisible(false);
			});
		}
		else{
			var ones = markers.filter(classFours);
			$.each(ones, function(i, marker){
				marker.setVisible(true);
			});
		}
	});
	
	$('#2wd').change(function(){
		if( !$(this)[0].checked ){
			var ones = markers.filter(twoWheelDrive);
			$.each(ones, function(i, marker){
				marker.setVisible(false);
			});
		}
		else{
			var ones = markers.filter(twoWheelDrive);
			$.each(ones, function(i, marker){
				marker.setVisible(true);
			});
		}
	});

	$('#2hc').change(function(){
		if( !$(this)[0].checked ){
			var ones = markers.filter(twoHighClearance);
			$.each(ones, function(i, marker){
				marker.setVisible(false);
			});
		}
		else{
			var ones = markers.filter(twoHighClearance);
			$.each(ones, function(i, marker){
				marker.setVisible(true);
			});
		}
	});

	$('#awd').change(function(){
		if( !$(this)[0].checked ){
			var ones = markers.filter(allWheelDrive);
			$.each(ones, function(i, marker){
				marker.setVisible(false);
			});
		}
		else{
			var ones = markers.filter(allWheelDrive);
			$.each(ones, function(i, marker){
				marker.setVisible(true);
			});
		}
	});

	$('#4x4').change(function(){
		if( !$(this)[0].checked ){
			var ones = markers.filter(fourByFour).filter;
			$.each(ones, function(i, marker){
				marker.setVisible(false);
			});
		}
		else{
			var ones = markers.filter(fourByFour);
			$.each(ones, function(i, marker){
				marker.setVisible(true);
			});
		}
	});

	function accessibility(num){
		if (num == 1) return "2 Wheel Drive";
		if (num == 2) return "High-Clearance 2WD";
		if (num == 3) return "AWD / 4X4 Recommended"
		else return "High-Clearance 4X4 Required";
	}

	$(function() {
		$("#slider-vehicle").slider({
			value: 4,
			// range: false,
			min: 1,
			max: 4,
			step: 1,
			slide: function(event, ui){
					$("#vehicle").val(accessibility(ui.value));
					$.each(markers.filter(visible), function(i, marker){
						if (marker.four_x_four_required > ui.value){
							marker.setVisible(false);
						}
						else{
							marker.setVisible(true);
						}
					});
					}
		});
		$("#vehicle").val(accessibility($("#slider-vehicle").slider("value")));

	});

	$(function() {
		$("#slider-elevation").slider({
			range: true,
			min: 1500,
			max: 7500,
			values: [0, 7500],
			slide: function( event, ui ) {
				$("#elevation").val(ui.values[0] + "ft - " + ui.values[ 1 ] + "ft");
				$.each(markers.filter(visible), function(i, marker){
					if (marker.elevation_gain_in_feet < ui.values[ 0 ] || marker.elevation_gain_in_feet > ui.values[ 1 ]) {
						marker.setVisible(false);
					} else {
						marker.setVisible(true);
					}
				});
			}
		});
		$( "#elevation" ).val($( "#slider-elevation" ).slider( "values", 0 ) + "ft - "
			+ $( "#slider-elevation" ).slider( "values", 1 ) + "ft" );
	});

	$(function() {
		$("#slider-distance").slider({
			range: true,
			min: 0,
			max: 26,
			values: [0, 26],
			slide: function(event, ui) {
				$("#distance").val(ui.values[0] + "miles - " + ui.values[ 1 ] + "miles");
				$.each(markers.filter(visible), function(i, marker){
					if (marker.round_trip_distance_in_miles < ui.values[ 0 ] || marker.round_trip_distance_in_miles > ui.values[ 1 ]) {
						marker.setVisible(false);
					} else {
						marker.setVisible(true);
					}
				});
			}
		});
		$("#distance").val($("#slider-distance").slider("values", 0) + " miles - "
			+ $("#slider-distance").slider("values", 1) + " miles");
	});


</script>

app/views/fourteeners/new.html.erb
<h1>New Fourteener</h1>

<%= render 'form', fourteener: @fourteener %>

<%= link_to 'Back', fourteeners_path %>

app/views/fourteeners/show.html.erb
<%= include_gon(:init => true) %>

<div id="map"></div>
  <script>
    function initMap() {
      var map = new google.maps.Map(document.getElementById('map'), {
          mapTypeId: 'terrain'
      });
      var ctaLayer = new google.maps.KmlLayer({
        url: gon.fourteener.kml,
          preserveViewport: false,
        map: map
      });
      google.maps.event.addListenerOnce(map, 'zoom_changed', function() {
        map.setZoom(13);
      });
    }

  </script>
  <script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBBYkGDkbDQBSWK4WoQM-r8tA5WXkqu_Rw&callback=initMap">
  </script>

  <div id="sidebar">
   <script type="text/javascript">
       if (gon.fourteener.surname == "Mount") {
         var full_name = gon.fourteener.surname +" " +gon.fourteener.name;
       } else if (gon.fourteener.surname == "Peak"){
         var full_name = gon.fourteener.name + " " +gon.fourteener.surname;
       } else if (gon.fourteener.surname == "Mount of the "){
         var full_name = gon.fourteener.surname +" "+gon.fourteener.name;
       } else if (gon.fourteener.surname == "Mountain"){
         var full_name = gon.fourteener.name +" " +gon.fourteener.surname;
       } else if (gon.fourteener.surname == "Needle"){
         var full_name = gon.fourteener.name +" " +gon.fourteener.surname;
       } else if (gon.fourteener.surname == "Point"){
         var full_name = gon.fourteener.name +" " +gon.fourteener.surname;
       } else {
         var full_name = gon.fourteener.name;
       }
       $("#sidebar").prepend("<h2>" + full_name + "</h2>");
       
   </script>
   <h5><%= @fourteener.elevation_in_feet; %> ft. </h5>
   <h6> ranked:  <%= @fourteener.rank; %>/53</h6>
   <h6> national forest: <%= @fourteener.forest; %> </h6>
   <h6> mountain range: <%= @fourteener.range; %> </h6>

   <br>
   <img src="https://raw.githubusercontent.com/elliotwhitehead/SummitPlan/4afd8aa869a0a999cd0583814833745dfe30ff7a/standardRoute.png"
   hspace="50" width="90px" height="45px">
   <h5> <%= @fourteener.trailhead_name; %> Trailhead </h5>
   <h6> <%= @fourteener.trailhead_lat; %>, <%= @fourteener.trailhead_long;%></h6>
   <h6> <%= @fourteener.route_name; %> </h6>
   <h6> Climbing Class:<%= @fourteener.classification; %> </h6>
   <h6> Exposure:<%= @fourteener.exposure; %> </h6>
   <h4> &harrw;  <%= @fourteener.round_trip_distance_in_miles; %> miles roundtrip  </h4>
   <h4>&#10169;  <%= @fourteener.elevation_gain_in_feet; %> foot elevation gain </h4>
   <!-- <h6> if you don't have a four wheel drive capable car </h6> -->






   
   
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<link href="https://raw.githubusercontent.com/elliotwhitehead/SummitPlan/b328da5613cf23a9f89d926b596505a48126f5f6/favicon.ico" rel="shortcut icon" type="image/x-icon" />
	<meta name="viewport" content="initial-scale=1.0, user-scalable=no">
	<meta charset="utf-8">

	<script
	src="https://code.jquery.com/jquery-1.12.4.min.js"
	integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
	crossorigin="anonymous"></script>

	<!-- Compiled and minified CSS -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">

	<!-- Compiled and minified JavaScript -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
	

	<title>SummitPlan</title>
	<%= csrf_meta_tags %>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<div class="flex-container">
		<header>
			<img src="https://github.com/elliotwhitehead/SummitPlan/blob/design/resizedWhiteLogo.png?raw=true" align="left">
			
			<br>
			<h1 style="font-size: 32px; padding-left: 30%;">The perfect tool for summiting Colorado's 14,000 foot peaks.</h1>
			<br>
			<br>
			<div class="row" style="background: black; height: 70px;">
				<div class="col s4">
					<a href="/" style="text-align:center; width: 100%; display:block; padding-top:30px; font-size: 20px;">Fourteener Filter</a>					
				</div>
				<div class="col s4">
					<svg width="100%" height="70">

					</svg>
				</div>
				<div class="col s4">
					<a href="/users/sign_in" style="text-align:center; width: 100%; display:block; padding-top:30px; font-size: 20px;">Login</a>					
				</div>
			</div>
			<!-- <svg width="100%" height="70">
				<rect width="100%" height="1000" style="fill:black" />
				<text x="5%" y="45" font-family="Futura" font-size="20" fill="gray">Fourteener Filter</text>
				<text x="30%" y="45" font-family="Futura" font-size="25" fill="white">&#9830</text>
				<text x="40%" y="45" font-family="Futura" font-size="20" fill="gray">Fourteener Profiles</text>
				<text x="65%" y="45" font-family="Futura" font-size="25" fill="white">&#9830</text>
				<text x="75%" y="45" font-family="Futura" font-size="20" fill="gray">Log In</text>
			</svg> -->
		</header>
	</div>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<%= yield %>
</body>
</html>